server:
  port: 9999 #\u670D\u52A1\u7AEF\u53E3
spring:
  application:
    name: springcloud-zuul #\u670D\u52A1\u540D
eureka:
  client:
    registry-fetch-interval-seconds: 5 # \u83B7\u53D6\u670D\u52A1\u5217\u8868\u7684\u5468\u671F\uFF1A5s
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
zuul:
  routes:
    service-provide: /service-provide/** # \u6620\u5C04\u8DEF\u5F84
    service-consume: /service-consume/**
  prefix: /api # \u6307\u5B9A\u8DEF\u7531\u524D\u7F00