server:
  port: 10086
spring:
  application:
    name: springcloud-eureka
eureka:
  client:
    service-url:
      defaultZone: http://www.leyou.com:${server.port}/eureka
  server:
    eviction-interval-timer-in-ms: 5000



